#!/usr/bin/env bash
#A bash script that does like the rest except it prints 
#Hi when on the 9th loop

i=0
while [ $i -lt 10 ]
do
    echo "Best School"
    if [ $i == 8 ];then
        echo "Hi"
    fi
    ((i++))
done
