#!/usr/bin/env bash
#A bash script that does like the rest except it prints 
#Hi when on the 9th loop

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
