#!/usr/bin/env bash

target_file="/root/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"

if test -f "$target_file";
then
    echo "school file exists"
else
    echo "school file does not exist"
fi
